apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: privatebin
  labels:
    app: privatebin
data:
  CONFIG_PATH: "/config"
  PRIVATEBIN_NAME: "PrivateBin"
  PRIVATEBIN_DISCUSSION_ENABLE: "true"
  PRIVATEBIN_DISCUSSION_DEFAULT: "false"
  PRIVATEBIN_PASSWORD_ENABLE: "true"
  PRIVATEBIN_FILEUPLOAD_ENABLE: "false"
  PRIVATEBIN_BURNAFTERREADING_DEFAULT: "false"
  PRIVATEBIN_FORMATTER_DEFAULT: "plaintext"
  PRIVATEBIN_SYNTAX_HIGHLIGHT_THEME: ""
  PRIVATEBIN_SIZE_LIMIT: "10485760"
  PRIVATEBIN_TEMPLATE: "bootstrap"
  PRIVATEBIN_NOTICE: "Note: This is a test service: Data may be deleted anytime. Kittens will die if you abuse this service."
  PRIVATEBIN_LANGUAGE_SELECTION: "true"
  PRIVATEBIN_LANGUAGE_DEFAULT: "en"
  PRIVATEBIN_URLSHORTENER_URL: ""
  PRIVATEBIN_QRCODE: "true"
  PRIVATEBIN_ICON: "identicon"
  PRIVATEBIN_ZEROBINCOMPATIBILITY: "false"
  PRIVATEBIN_HTTP_WARNING: "true"
  PRIVATEBIN_COMPRESSION: "zlib"
  PRIVATEBIN_RATE_LIMIT: "10"
  PRIVATEBIN_REAL_IP_HEADER: "X_FORWARDED_FOR"
  PRIVATEBIN_STORAGE: "filesystem"
  PRIVATEBIN_DATA_PATH: "/data"
  PRIVATEBIN_MYSQL_HOST: "mysql"
  PRIVATEBIN_MYSQL_DATABASE: "privatebin"
  PRIVATEBIN_MYSQL_TABLE_PREFIX: "pb_"
  PRIVATEBIN_MYSQL_USERNAME: "privatebin"
  PRIVATEBIN_MYSQL_PASSWORD: "Y0uMustChang3M3"
  PRIVATEBIN_MYSQL_ATTR_PERSISTENT: "true"
  PRIVATEBIN_SQLITE_DB_PATH: "/data/db.sq3"
  PRIVATEBIN_SQLITE_ATTR_PERSISTENT: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: privatebin
  name: privatebin
spec:
  selector:
    matchLabels:
      app: privatebin
  template:
    metadata:
      labels:
        app: privatebin
    spec:
      containers:
      - name: privatebin
        envFrom:
        - configMapRef:
            name: privatebin
        volumeMounts:
        - mountPath: /data
          name: data
        image: infrabuilder/privatebin:1.3.4
        imagePullPolicy: IfNotPresent
        resources: {}
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: privatebin-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: privatebin
  name: privatebin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: privatebin
  sessionAffinity: None
  type: ClusterIP